name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set environment variables
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Run release script
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          chmod +x ./scripts/release.sh
          ./scripts/release.sh ${{ env.TAG_NAME }} true

      - name: Commit and push changes
        run: |
          VERSION=${TAG_NAME#v}
          # Checkout the main branch to avoid detached HEAD state
          git fetch origin
          git checkout brew
          
          # Run the release script again to update files on the branch
          ./scripts/release.sh ${{ env.TAG_NAME }} true
          
          # Commit and push changes
          git add lua/vlip/cli.lua homebrew-vlip/Formula/vlip.rb
          git commit -m "Release ${{ env.TAG_NAME }}" || echo "No changes to commit"
          git push origin brew