name: Test Homebrew Formula

on:
  push:
    branches: [ main ]
    paths:
      - 'homebrew-vlip/**'
      - 'lua/**'
      - 'bin/**'
      - 'vlip-scm-1.rockspec'
  pull_request:
    branches: [ main ]
    paths:
      - 'homebrew-vlip/**'
      - 'lua/**'
      - 'bin/**'
      - 'vlip-scm-1.rockspec'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Homebrew
        run: |
          brew update
      
      - name: Test formula
        run: |
          chmod +x ./homebrew-vlip/test-formula.sh
          ./homebrew-vlip/test-formula.sh
